// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: api/proto/v1/service.proto

package pb

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	_ "google.golang.org/genproto/googleapis/rpc/code"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateTweetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTweetRequest) Reset() {
	*x = CreateTweetRequest{}
	mi := &file_api_proto_v1_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTweetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTweetRequest) ProtoMessage() {}

func (x *CreateTweetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTweetRequest.ProtoReflect.Descriptor instead.
func (*CreateTweetRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_service_proto_rawDescGZIP(), []int{0}
}

func (x *CreateTweetRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type CreateTweetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tweet         *Tweet                 `protobuf:"bytes,1,opt,name=tweet,proto3" json:"tweet,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTweetResponse) Reset() {
	*x = CreateTweetResponse{}
	mi := &file_api_proto_v1_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTweetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTweetResponse) ProtoMessage() {}

func (x *CreateTweetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTweetResponse.ProtoReflect.Descriptor instead.
func (*CreateTweetResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_service_proto_rawDescGZIP(), []int{1}
}

func (x *CreateTweetResponse) GetTweet() *Tweet {
	if x != nil {
		return x.Tweet
	}
	return nil
}

type GetTweetByIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTweetByIDRequest) Reset() {
	*x = GetTweetByIDRequest{}
	mi := &file_api_proto_v1_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTweetByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTweetByIDRequest) ProtoMessage() {}

func (x *GetTweetByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTweetByIDRequest.ProtoReflect.Descriptor instead.
func (*GetTweetByIDRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_service_proto_rawDescGZIP(), []int{2}
}

func (x *GetTweetByIDRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetTweetByIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tweet         *Tweet                 `protobuf:"bytes,1,opt,name=tweet,proto3" json:"tweet,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTweetByIDResponse) Reset() {
	*x = GetTweetByIDResponse{}
	mi := &file_api_proto_v1_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTweetByIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTweetByIDResponse) ProtoMessage() {}

func (x *GetTweetByIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTweetByIDResponse.ProtoReflect.Descriptor instead.
func (*GetTweetByIDResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_service_proto_rawDescGZIP(), []int{3}
}

func (x *GetTweetByIDResponse) GetTweet() *Tweet {
	if x != nil {
		return x.Tweet
	}
	return nil
}

type GetUserTweetsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserTweetsRequest) Reset() {
	*x = GetUserTweetsRequest{}
	mi := &file_api_proto_v1_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserTweetsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserTweetsRequest) ProtoMessage() {}

func (x *GetUserTweetsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserTweetsRequest.ProtoReflect.Descriptor instead.
func (*GetUserTweetsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_service_proto_rawDescGZIP(), []int{4}
}

func (x *GetUserTweetsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetUserTweetsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tweets        []*Tweet               `protobuf:"bytes,1,rep,name=tweets,proto3" json:"tweets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserTweetsResponse) Reset() {
	*x = GetUserTweetsResponse{}
	mi := &file_api_proto_v1_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserTweetsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserTweetsResponse) ProtoMessage() {}

func (x *GetUserTweetsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserTweetsResponse.ProtoReflect.Descriptor instead.
func (*GetUserTweetsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_service_proto_rawDescGZIP(), []int{5}
}

func (x *GetUserTweetsResponse) GetTweets() []*Tweet {
	if x != nil {
		return x.Tweets
	}
	return nil
}

type UpdateTweetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTweetRequest) Reset() {
	*x = UpdateTweetRequest{}
	mi := &file_api_proto_v1_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTweetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTweetRequest) ProtoMessage() {}

func (x *UpdateTweetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTweetRequest.ProtoReflect.Descriptor instead.
func (*UpdateTweetRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_service_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateTweetRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateTweetRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type UpdateTweetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tweet         *Tweet                 `protobuf:"bytes,1,opt,name=tweet,proto3" json:"tweet,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTweetResponse) Reset() {
	*x = UpdateTweetResponse{}
	mi := &file_api_proto_v1_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTweetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTweetResponse) ProtoMessage() {}

func (x *UpdateTweetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTweetResponse.ProtoReflect.Descriptor instead.
func (*UpdateTweetResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_service_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateTweetResponse) GetTweet() *Tweet {
	if x != nil {
		return x.Tweet
	}
	return nil
}

type DeleteTweetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTweetRequest) Reset() {
	*x = DeleteTweetRequest{}
	mi := &file_api_proto_v1_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTweetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTweetRequest) ProtoMessage() {}

func (x *DeleteTweetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTweetRequest.ProtoReflect.Descriptor instead.
func (*DeleteTweetRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_service_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteTweetRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteTweetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTweetResponse) Reset() {
	*x = DeleteTweetResponse{}
	mi := &file_api_proto_v1_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTweetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTweetResponse) ProtoMessage() {}

func (x *DeleteTweetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTweetResponse.ProtoReflect.Descriptor instead.
func (*DeleteTweetResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_service_proto_rawDescGZIP(), []int{9}
}

type GetSubscribersTweetsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserIds       []string               `protobuf:"bytes,1,rep,name=user_ids,json=userIds,proto3" json:"user_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSubscribersTweetsRequest) Reset() {
	*x = GetSubscribersTweetsRequest{}
	mi := &file_api_proto_v1_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSubscribersTweetsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSubscribersTweetsRequest) ProtoMessage() {}

func (x *GetSubscribersTweetsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSubscribersTweetsRequest.ProtoReflect.Descriptor instead.
func (*GetSubscribersTweetsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_service_proto_rawDescGZIP(), []int{10}
}

func (x *GetSubscribersTweetsRequest) GetUserIds() []string {
	if x != nil {
		return x.UserIds
	}
	return nil
}

type GetSubscribersTweetsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tweets        []*Tweet               `protobuf:"bytes,1,rep,name=tweets,proto3" json:"tweets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSubscribersTweetsResponse) Reset() {
	*x = GetSubscribersTweetsResponse{}
	mi := &file_api_proto_v1_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSubscribersTweetsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSubscribersTweetsResponse) ProtoMessage() {}

func (x *GetSubscribersTweetsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSubscribersTweetsResponse.ProtoReflect.Descriptor instead.
func (*GetSubscribersTweetsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_service_proto_rawDescGZIP(), []int{11}
}

func (x *GetSubscribersTweetsResponse) GetTweets() []*Tweet {
	if x != nil {
		return x.Tweets
	}
	return nil
}

type Tweet struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	UserId        string                 `protobuf:"bytes,5,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Tweet) Reset() {
	*x = Tweet{}
	mi := &file_api_proto_v1_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tweet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tweet) ProtoMessage() {}

func (x *Tweet) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tweet.ProtoReflect.Descriptor instead.
func (*Tweet) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_service_proto_rawDescGZIP(), []int{12}
}

func (x *Tweet) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Tweet) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *Tweet) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Tweet) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Tweet) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

var File_api_proto_v1_service_proto protoreflect.FileDescriptor

const file_api_proto_v1_service_proto_rawDesc = "" +
	"\n" +
	"\x1aapi/proto/v1/service.proto\x12\fapi.proto.v1\x1a\x17validate/validate.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x15google/rpc/code.proto\"4\n" +
	"\x12CreateTweetRequest\x12\x1e\n" +
	"\x04text\x18\x01 \x01(\tB\n" +
	"\xfaB\ar\x05\x10\x01\x18\xfa\x01R\x04text\"@\n" +
	"\x13CreateTweetResponse\x12)\n" +
	"\x05tweet\x18\x01 \x01(\v2\x13.api.proto.v1.TweetR\x05tweet\"/\n" +
	"\x13GetTweetByIDRequest\x12\x18\n" +
	"\x02id\x18\x01 \x01(\tB\b\xfaB\x05r\x03\xb0\x01\x01R\x02id\"A\n" +
	"\x14GetTweetByIDResponse\x12)\n" +
	"\x05tweet\x18\x01 \x01(\v2\x13.api.proto.v1.TweetR\x05tweet\"9\n" +
	"\x14GetUserTweetsRequest\x12!\n" +
	"\auser_id\x18\x01 \x01(\tB\b\xfaB\x05r\x03\xb0\x01\x01R\x06userId\"D\n" +
	"\x15GetUserTweetsResponse\x12+\n" +
	"\x06tweets\x18\x01 \x03(\v2\x13.api.proto.v1.TweetR\x06tweets\"N\n" +
	"\x12UpdateTweetRequest\x12\x18\n" +
	"\x02id\x18\x01 \x01(\tB\b\xfaB\x05r\x03\xb0\x01\x01R\x02id\x12\x1e\n" +
	"\x04text\x18\x02 \x01(\tB\n" +
	"\xfaB\ar\x05\x10\x01\x18\xfa\x01R\x04text\"@\n" +
	"\x13UpdateTweetResponse\x12)\n" +
	"\x05tweet\x18\x01 \x01(\v2\x13.api.proto.v1.TweetR\x05tweet\".\n" +
	"\x12DeleteTweetRequest\x12\x18\n" +
	"\x02id\x18\x01 \x01(\tB\b\xfaB\x05r\x03\xb0\x01\x01R\x02id\"\x15\n" +
	"\x13DeleteTweetResponse\"8\n" +
	"\x1bGetSubscribersTweetsRequest\x12\x19\n" +
	"\buser_ids\x18\x01 \x03(\tR\auserIds\"K\n" +
	"\x1cGetSubscribersTweetsResponse\x12+\n" +
	"\x06tweets\x18\x01 \x03(\v2\x13.api.proto.v1.TweetR\x06tweets\"\xda\x01\n" +
	"\x05Tweet\x12\x18\n" +
	"\x02id\x18\x01 \x01(\tB\b\xfaB\x05r\x03\xb0\x01\x01R\x02id\x12\x1e\n" +
	"\x04text\x18\x02 \x01(\tB\n" +
	"\xfaB\ar\x05\x10\x01\x18\xfa\x01R\x04text\x129\n" +
	"\n" +
	"created_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12!\n" +
	"\auser_id\x18\x05 \x01(\tB\b\xfaB\x05r\x03\xb0\x01\x01R\x06userId2\xbd\x05\n" +
	"\n" +
	"TwitterAPI\x12f\n" +
	"\vCreateTweet\x12 .api.proto.v1.CreateTweetRequest\x1a!.api.proto.v1.CreateTweetResponse\"\x12\x82\xd3\xe4\x93\x02\f:\x01*\"\a/tweets\x12k\n" +
	"\fGetTweetByID\x12!.api.proto.v1.GetTweetByIDRequest\x1a\".api.proto.v1.GetTweetByIDResponse\"\x14\x82\xd3\xe4\x93\x02\x0e\x12\f/tweets/{id}\x12y\n" +
	"\rGetUserTweets\x12\".api.proto.v1.GetUserTweetsRequest\x1a#.api.proto.v1.GetUserTweetsResponse\"\x1f\x82\xd3\xe4\x93\x02\x19\x12\x17/users/{user_id}/tweets\x12k\n" +
	"\vUpdateTweet\x12 .api.proto.v1.UpdateTweetRequest\x1a!.api.proto.v1.UpdateTweetResponse\"\x17\x82\xd3\xe4\x93\x02\x11:\x01*\x1a\f/tweets/{id}\x12h\n" +
	"\vDeleteTweet\x12 .api.proto.v1.DeleteTweetRequest\x1a!.api.proto.v1.DeleteTweetResponse\"\x14\x82\xd3\xe4\x93\x02\x0e*\f/tweets/{id}\x12\x87\x01\n" +
	"\x14GetSubscribersTweets\x12).api.proto.v1.GetSubscribersTweetsRequest\x1a*.api.proto.v1.GetSubscribersTweetsResponse\"\x18\x82\xd3\xe4\x93\x02\x12:\x01*\"\r/tweets/usersB\x06Z\x04.;pbb\x06proto3"

var (
	file_api_proto_v1_service_proto_rawDescOnce sync.Once
	file_api_proto_v1_service_proto_rawDescData []byte
)

func file_api_proto_v1_service_proto_rawDescGZIP() []byte {
	file_api_proto_v1_service_proto_rawDescOnce.Do(func() {
		file_api_proto_v1_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_v1_service_proto_rawDesc), len(file_api_proto_v1_service_proto_rawDesc)))
	})
	return file_api_proto_v1_service_proto_rawDescData
}

var file_api_proto_v1_service_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_api_proto_v1_service_proto_goTypes = []any{
	(*CreateTweetRequest)(nil),           // 0: api.proto.v1.CreateTweetRequest
	(*CreateTweetResponse)(nil),          // 1: api.proto.v1.CreateTweetResponse
	(*GetTweetByIDRequest)(nil),          // 2: api.proto.v1.GetTweetByIDRequest
	(*GetTweetByIDResponse)(nil),         // 3: api.proto.v1.GetTweetByIDResponse
	(*GetUserTweetsRequest)(nil),         // 4: api.proto.v1.GetUserTweetsRequest
	(*GetUserTweetsResponse)(nil),        // 5: api.proto.v1.GetUserTweetsResponse
	(*UpdateTweetRequest)(nil),           // 6: api.proto.v1.UpdateTweetRequest
	(*UpdateTweetResponse)(nil),          // 7: api.proto.v1.UpdateTweetResponse
	(*DeleteTweetRequest)(nil),           // 8: api.proto.v1.DeleteTweetRequest
	(*DeleteTweetResponse)(nil),          // 9: api.proto.v1.DeleteTweetResponse
	(*GetSubscribersTweetsRequest)(nil),  // 10: api.proto.v1.GetSubscribersTweetsRequest
	(*GetSubscribersTweetsResponse)(nil), // 11: api.proto.v1.GetSubscribersTweetsResponse
	(*Tweet)(nil),                        // 12: api.proto.v1.Tweet
	(*timestamppb.Timestamp)(nil),        // 13: google.protobuf.Timestamp
}
var file_api_proto_v1_service_proto_depIdxs = []int32{
	12, // 0: api.proto.v1.CreateTweetResponse.tweet:type_name -> api.proto.v1.Tweet
	12, // 1: api.proto.v1.GetTweetByIDResponse.tweet:type_name -> api.proto.v1.Tweet
	12, // 2: api.proto.v1.GetUserTweetsResponse.tweets:type_name -> api.proto.v1.Tweet
	12, // 3: api.proto.v1.UpdateTweetResponse.tweet:type_name -> api.proto.v1.Tweet
	12, // 4: api.proto.v1.GetSubscribersTweetsResponse.tweets:type_name -> api.proto.v1.Tweet
	13, // 5: api.proto.v1.Tweet.created_at:type_name -> google.protobuf.Timestamp
	13, // 6: api.proto.v1.Tweet.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 7: api.proto.v1.TwitterAPI.CreateTweet:input_type -> api.proto.v1.CreateTweetRequest
	2,  // 8: api.proto.v1.TwitterAPI.GetTweetByID:input_type -> api.proto.v1.GetTweetByIDRequest
	4,  // 9: api.proto.v1.TwitterAPI.GetUserTweets:input_type -> api.proto.v1.GetUserTweetsRequest
	6,  // 10: api.proto.v1.TwitterAPI.UpdateTweet:input_type -> api.proto.v1.UpdateTweetRequest
	8,  // 11: api.proto.v1.TwitterAPI.DeleteTweet:input_type -> api.proto.v1.DeleteTweetRequest
	10, // 12: api.proto.v1.TwitterAPI.GetSubscribersTweets:input_type -> api.proto.v1.GetSubscribersTweetsRequest
	1,  // 13: api.proto.v1.TwitterAPI.CreateTweet:output_type -> api.proto.v1.CreateTweetResponse
	3,  // 14: api.proto.v1.TwitterAPI.GetTweetByID:output_type -> api.proto.v1.GetTweetByIDResponse
	5,  // 15: api.proto.v1.TwitterAPI.GetUserTweets:output_type -> api.proto.v1.GetUserTweetsResponse
	7,  // 16: api.proto.v1.TwitterAPI.UpdateTweet:output_type -> api.proto.v1.UpdateTweetResponse
	9,  // 17: api.proto.v1.TwitterAPI.DeleteTweet:output_type -> api.proto.v1.DeleteTweetResponse
	11, // 18: api.proto.v1.TwitterAPI.GetSubscribersTweets:output_type -> api.proto.v1.GetSubscribersTweetsResponse
	13, // [13:19] is the sub-list for method output_type
	7,  // [7:13] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_api_proto_v1_service_proto_init() }
func file_api_proto_v1_service_proto_init() {
	if File_api_proto_v1_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_v1_service_proto_rawDesc), len(file_api_proto_v1_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_v1_service_proto_goTypes,
		DependencyIndexes: file_api_proto_v1_service_proto_depIdxs,
		MessageInfos:      file_api_proto_v1_service_proto_msgTypes,
	}.Build()
	File_api_proto_v1_service_proto = out.File
	file_api_proto_v1_service_proto_goTypes = nil
	file_api_proto_v1_service_proto_depIdxs = nil
}
