// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: api/proto/v1/service.proto

package pb

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// define the regex for a UUID once up-front
var _service_uuidPattern = regexp.MustCompile("^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$")

// Validate checks the field values on CreateTweetRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CreateTweetRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CreateTweetRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CreateTweetRequestMultiError, or nil if none found.
func (m *CreateTweetRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *CreateTweetRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if l := utf8.RuneCountInString(m.GetText()); l < 1 || l > 250 {
		err := CreateTweetRequestValidationError{
			field:  "Text",
			reason: "value length must be between 1 and 250 runes, inclusive",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return CreateTweetRequestMultiError(errors)
	}

	return nil
}

// CreateTweetRequestMultiError is an error wrapping multiple validation errors
// returned by CreateTweetRequest.ValidateAll() if the designated constraints
// aren't met.
type CreateTweetRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreateTweetRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreateTweetRequestMultiError) AllErrors() []error { return m }

// CreateTweetRequestValidationError is the validation error returned by
// CreateTweetRequest.Validate if the designated constraints aren't met.
type CreateTweetRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateTweetRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateTweetRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateTweetRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateTweetRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateTweetRequestValidationError) ErrorName() string {
	return "CreateTweetRequestValidationError"
}

// Error satisfies the builtin error interface
func (e CreateTweetRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateTweetRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateTweetRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateTweetRequestValidationError{}

// Validate checks the field values on CreateTweetResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CreateTweetResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CreateTweetResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CreateTweetResponseMultiError, or nil if none found.
func (m *CreateTweetResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *CreateTweetResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetTweet()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, CreateTweetResponseValidationError{
					field:  "Tweet",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, CreateTweetResponseValidationError{
					field:  "Tweet",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetTweet()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return CreateTweetResponseValidationError{
				field:  "Tweet",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return CreateTweetResponseMultiError(errors)
	}

	return nil
}

// CreateTweetResponseMultiError is an error wrapping multiple validation
// errors returned by CreateTweetResponse.ValidateAll() if the designated
// constraints aren't met.
type CreateTweetResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreateTweetResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreateTweetResponseMultiError) AllErrors() []error { return m }

// CreateTweetResponseValidationError is the validation error returned by
// CreateTweetResponse.Validate if the designated constraints aren't met.
type CreateTweetResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateTweetResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateTweetResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateTweetResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateTweetResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateTweetResponseValidationError) ErrorName() string {
	return "CreateTweetResponseValidationError"
}

// Error satisfies the builtin error interface
func (e CreateTweetResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateTweetResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateTweetResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateTweetResponseValidationError{}

// Validate checks the field values on GetTweetByIDRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetTweetByIDRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetTweetByIDRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetTweetByIDRequestMultiError, or nil if none found.
func (m *GetTweetByIDRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetTweetByIDRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if err := m._validateUuid(m.GetId()); err != nil {
		err = GetTweetByIDRequestValidationError{
			field:  "Id",
			reason: "value must be a valid UUID",
			cause:  err,
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return GetTweetByIDRequestMultiError(errors)
	}

	return nil
}

func (m *GetTweetByIDRequest) _validateUuid(uuid string) error {
	if matched := _service_uuidPattern.MatchString(uuid); !matched {
		return errors.New("invalid uuid format")
	}

	return nil
}

// GetTweetByIDRequestMultiError is an error wrapping multiple validation
// errors returned by GetTweetByIDRequest.ValidateAll() if the designated
// constraints aren't met.
type GetTweetByIDRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetTweetByIDRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetTweetByIDRequestMultiError) AllErrors() []error { return m }

// GetTweetByIDRequestValidationError is the validation error returned by
// GetTweetByIDRequest.Validate if the designated constraints aren't met.
type GetTweetByIDRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetTweetByIDRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetTweetByIDRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetTweetByIDRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetTweetByIDRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetTweetByIDRequestValidationError) ErrorName() string {
	return "GetTweetByIDRequestValidationError"
}

// Error satisfies the builtin error interface
func (e GetTweetByIDRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetTweetByIDRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetTweetByIDRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetTweetByIDRequestValidationError{}

// Validate checks the field values on GetTweetByIDResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetTweetByIDResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetTweetByIDResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetTweetByIDResponseMultiError, or nil if none found.
func (m *GetTweetByIDResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *GetTweetByIDResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetTweet()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, GetTweetByIDResponseValidationError{
					field:  "Tweet",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, GetTweetByIDResponseValidationError{
					field:  "Tweet",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetTweet()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return GetTweetByIDResponseValidationError{
				field:  "Tweet",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return GetTweetByIDResponseMultiError(errors)
	}

	return nil
}

// GetTweetByIDResponseMultiError is an error wrapping multiple validation
// errors returned by GetTweetByIDResponse.ValidateAll() if the designated
// constraints aren't met.
type GetTweetByIDResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetTweetByIDResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetTweetByIDResponseMultiError) AllErrors() []error { return m }

// GetTweetByIDResponseValidationError is the validation error returned by
// GetTweetByIDResponse.Validate if the designated constraints aren't met.
type GetTweetByIDResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetTweetByIDResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetTweetByIDResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetTweetByIDResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetTweetByIDResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetTweetByIDResponseValidationError) ErrorName() string {
	return "GetTweetByIDResponseValidationError"
}

// Error satisfies the builtin error interface
func (e GetTweetByIDResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetTweetByIDResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetTweetByIDResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetTweetByIDResponseValidationError{}

// Validate checks the field values on GetUserTweetsRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetUserTweetsRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetUserTweetsRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetUserTweetsRequestMultiError, or nil if none found.
func (m *GetUserTweetsRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetUserTweetsRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if err := m._validateUuid(m.GetUserId()); err != nil {
		err = GetUserTweetsRequestValidationError{
			field:  "UserId",
			reason: "value must be a valid UUID",
			cause:  err,
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return GetUserTweetsRequestMultiError(errors)
	}

	return nil
}

func (m *GetUserTweetsRequest) _validateUuid(uuid string) error {
	if matched := _service_uuidPattern.MatchString(uuid); !matched {
		return errors.New("invalid uuid format")
	}

	return nil
}

// GetUserTweetsRequestMultiError is an error wrapping multiple validation
// errors returned by GetUserTweetsRequest.ValidateAll() if the designated
// constraints aren't met.
type GetUserTweetsRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetUserTweetsRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetUserTweetsRequestMultiError) AllErrors() []error { return m }

// GetUserTweetsRequestValidationError is the validation error returned by
// GetUserTweetsRequest.Validate if the designated constraints aren't met.
type GetUserTweetsRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetUserTweetsRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetUserTweetsRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetUserTweetsRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetUserTweetsRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetUserTweetsRequestValidationError) ErrorName() string {
	return "GetUserTweetsRequestValidationError"
}

// Error satisfies the builtin error interface
func (e GetUserTweetsRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetUserTweetsRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetUserTweetsRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetUserTweetsRequestValidationError{}

// Validate checks the field values on GetUserTweetsResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetUserTweetsResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetUserTweetsResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetUserTweetsResponseMultiError, or nil if none found.
func (m *GetUserTweetsResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *GetUserTweetsResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetTweets() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, GetUserTweetsResponseValidationError{
						field:  fmt.Sprintf("Tweets[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, GetUserTweetsResponseValidationError{
						field:  fmt.Sprintf("Tweets[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return GetUserTweetsResponseValidationError{
					field:  fmt.Sprintf("Tweets[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return GetUserTweetsResponseMultiError(errors)
	}

	return nil
}

// GetUserTweetsResponseMultiError is an error wrapping multiple validation
// errors returned by GetUserTweetsResponse.ValidateAll() if the designated
// constraints aren't met.
type GetUserTweetsResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetUserTweetsResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetUserTweetsResponseMultiError) AllErrors() []error { return m }

// GetUserTweetsResponseValidationError is the validation error returned by
// GetUserTweetsResponse.Validate if the designated constraints aren't met.
type GetUserTweetsResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetUserTweetsResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetUserTweetsResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetUserTweetsResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetUserTweetsResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetUserTweetsResponseValidationError) ErrorName() string {
	return "GetUserTweetsResponseValidationError"
}

// Error satisfies the builtin error interface
func (e GetUserTweetsResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetUserTweetsResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetUserTweetsResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetUserTweetsResponseValidationError{}

// Validate checks the field values on UpdateTweetRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *UpdateTweetRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UpdateTweetRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// UpdateTweetRequestMultiError, or nil if none found.
func (m *UpdateTweetRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *UpdateTweetRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if err := m._validateUuid(m.GetId()); err != nil {
		err = UpdateTweetRequestValidationError{
			field:  "Id",
			reason: "value must be a valid UUID",
			cause:  err,
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if l := utf8.RuneCountInString(m.GetText()); l < 1 || l > 250 {
		err := UpdateTweetRequestValidationError{
			field:  "Text",
			reason: "value length must be between 1 and 250 runes, inclusive",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return UpdateTweetRequestMultiError(errors)
	}

	return nil
}

func (m *UpdateTweetRequest) _validateUuid(uuid string) error {
	if matched := _service_uuidPattern.MatchString(uuid); !matched {
		return errors.New("invalid uuid format")
	}

	return nil
}

// UpdateTweetRequestMultiError is an error wrapping multiple validation errors
// returned by UpdateTweetRequest.ValidateAll() if the designated constraints
// aren't met.
type UpdateTweetRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UpdateTweetRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UpdateTweetRequestMultiError) AllErrors() []error { return m }

// UpdateTweetRequestValidationError is the validation error returned by
// UpdateTweetRequest.Validate if the designated constraints aren't met.
type UpdateTweetRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UpdateTweetRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UpdateTweetRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UpdateTweetRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UpdateTweetRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UpdateTweetRequestValidationError) ErrorName() string {
	return "UpdateTweetRequestValidationError"
}

// Error satisfies the builtin error interface
func (e UpdateTweetRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUpdateTweetRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UpdateTweetRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UpdateTweetRequestValidationError{}

// Validate checks the field values on UpdateTweetResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *UpdateTweetResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UpdateTweetResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// UpdateTweetResponseMultiError, or nil if none found.
func (m *UpdateTweetResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *UpdateTweetResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetTweet()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, UpdateTweetResponseValidationError{
					field:  "Tweet",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, UpdateTweetResponseValidationError{
					field:  "Tweet",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetTweet()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return UpdateTweetResponseValidationError{
				field:  "Tweet",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return UpdateTweetResponseMultiError(errors)
	}

	return nil
}

// UpdateTweetResponseMultiError is an error wrapping multiple validation
// errors returned by UpdateTweetResponse.ValidateAll() if the designated
// constraints aren't met.
type UpdateTweetResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UpdateTweetResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UpdateTweetResponseMultiError) AllErrors() []error { return m }

// UpdateTweetResponseValidationError is the validation error returned by
// UpdateTweetResponse.Validate if the designated constraints aren't met.
type UpdateTweetResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UpdateTweetResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UpdateTweetResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UpdateTweetResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UpdateTweetResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UpdateTweetResponseValidationError) ErrorName() string {
	return "UpdateTweetResponseValidationError"
}

// Error satisfies the builtin error interface
func (e UpdateTweetResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUpdateTweetResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UpdateTweetResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UpdateTweetResponseValidationError{}

// Validate checks the field values on DeleteTweetRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *DeleteTweetRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DeleteTweetRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// DeleteTweetRequestMultiError, or nil if none found.
func (m *DeleteTweetRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *DeleteTweetRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if err := m._validateUuid(m.GetId()); err != nil {
		err = DeleteTweetRequestValidationError{
			field:  "Id",
			reason: "value must be a valid UUID",
			cause:  err,
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return DeleteTweetRequestMultiError(errors)
	}

	return nil
}

func (m *DeleteTweetRequest) _validateUuid(uuid string) error {
	if matched := _service_uuidPattern.MatchString(uuid); !matched {
		return errors.New("invalid uuid format")
	}

	return nil
}

// DeleteTweetRequestMultiError is an error wrapping multiple validation errors
// returned by DeleteTweetRequest.ValidateAll() if the designated constraints
// aren't met.
type DeleteTweetRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DeleteTweetRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DeleteTweetRequestMultiError) AllErrors() []error { return m }

// DeleteTweetRequestValidationError is the validation error returned by
// DeleteTweetRequest.Validate if the designated constraints aren't met.
type DeleteTweetRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DeleteTweetRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DeleteTweetRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DeleteTweetRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DeleteTweetRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DeleteTweetRequestValidationError) ErrorName() string {
	return "DeleteTweetRequestValidationError"
}

// Error satisfies the builtin error interface
func (e DeleteTweetRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDeleteTweetRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DeleteTweetRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DeleteTweetRequestValidationError{}

// Validate checks the field values on DeleteTweetResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *DeleteTweetResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DeleteTweetResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// DeleteTweetResponseMultiError, or nil if none found.
func (m *DeleteTweetResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *DeleteTweetResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return DeleteTweetResponseMultiError(errors)
	}

	return nil
}

// DeleteTweetResponseMultiError is an error wrapping multiple validation
// errors returned by DeleteTweetResponse.ValidateAll() if the designated
// constraints aren't met.
type DeleteTweetResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DeleteTweetResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DeleteTweetResponseMultiError) AllErrors() []error { return m }

// DeleteTweetResponseValidationError is the validation error returned by
// DeleteTweetResponse.Validate if the designated constraints aren't met.
type DeleteTweetResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DeleteTweetResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DeleteTweetResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DeleteTweetResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DeleteTweetResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DeleteTweetResponseValidationError) ErrorName() string {
	return "DeleteTweetResponseValidationError"
}

// Error satisfies the builtin error interface
func (e DeleteTweetResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDeleteTweetResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DeleteTweetResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DeleteTweetResponseValidationError{}

// Validate checks the field values on GetSubscribersTweetsRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetSubscribersTweetsRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetSubscribersTweetsRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetSubscribersTweetsRequestMultiError, or nil if none found.
func (m *GetSubscribersTweetsRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetSubscribersTweetsRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return GetSubscribersTweetsRequestMultiError(errors)
	}

	return nil
}

// GetSubscribersTweetsRequestMultiError is an error wrapping multiple
// validation errors returned by GetSubscribersTweetsRequest.ValidateAll() if
// the designated constraints aren't met.
type GetSubscribersTweetsRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetSubscribersTweetsRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetSubscribersTweetsRequestMultiError) AllErrors() []error { return m }

// GetSubscribersTweetsRequestValidationError is the validation error returned
// by GetSubscribersTweetsRequest.Validate if the designated constraints
// aren't met.
type GetSubscribersTweetsRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetSubscribersTweetsRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetSubscribersTweetsRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetSubscribersTweetsRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetSubscribersTweetsRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetSubscribersTweetsRequestValidationError) ErrorName() string {
	return "GetSubscribersTweetsRequestValidationError"
}

// Error satisfies the builtin error interface
func (e GetSubscribersTweetsRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetSubscribersTweetsRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetSubscribersTweetsRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetSubscribersTweetsRequestValidationError{}

// Validate checks the field values on GetSubscribersTweetsResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetSubscribersTweetsResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetSubscribersTweetsResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetSubscribersTweetsResponseMultiError, or nil if none found.
func (m *GetSubscribersTweetsResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *GetSubscribersTweetsResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetTweets() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, GetSubscribersTweetsResponseValidationError{
						field:  fmt.Sprintf("Tweets[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, GetSubscribersTweetsResponseValidationError{
						field:  fmt.Sprintf("Tweets[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return GetSubscribersTweetsResponseValidationError{
					field:  fmt.Sprintf("Tweets[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return GetSubscribersTweetsResponseMultiError(errors)
	}

	return nil
}

// GetSubscribersTweetsResponseMultiError is an error wrapping multiple
// validation errors returned by GetSubscribersTweetsResponse.ValidateAll() if
// the designated constraints aren't met.
type GetSubscribersTweetsResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetSubscribersTweetsResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetSubscribersTweetsResponseMultiError) AllErrors() []error { return m }

// GetSubscribersTweetsResponseValidationError is the validation error returned
// by GetSubscribersTweetsResponse.Validate if the designated constraints
// aren't met.
type GetSubscribersTweetsResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetSubscribersTweetsResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetSubscribersTweetsResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetSubscribersTweetsResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetSubscribersTweetsResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetSubscribersTweetsResponseValidationError) ErrorName() string {
	return "GetSubscribersTweetsResponseValidationError"
}

// Error satisfies the builtin error interface
func (e GetSubscribersTweetsResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetSubscribersTweetsResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetSubscribersTweetsResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetSubscribersTweetsResponseValidationError{}

// Validate checks the field values on Tweet with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *Tweet) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Tweet with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in TweetMultiError, or nil if none found.
func (m *Tweet) ValidateAll() error {
	return m.validate(true)
}

func (m *Tweet) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if err := m._validateUuid(m.GetId()); err != nil {
		err = TweetValidationError{
			field:  "Id",
			reason: "value must be a valid UUID",
			cause:  err,
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if l := utf8.RuneCountInString(m.GetText()); l < 1 || l > 250 {
		err := TweetValidationError{
			field:  "Text",
			reason: "value length must be between 1 and 250 runes, inclusive",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if all {
		switch v := interface{}(m.GetCreatedAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, TweetValidationError{
					field:  "CreatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, TweetValidationError{
					field:  "CreatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetCreatedAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return TweetValidationError{
				field:  "CreatedAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetUpdatedAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, TweetValidationError{
					field:  "UpdatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, TweetValidationError{
					field:  "UpdatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetUpdatedAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return TweetValidationError{
				field:  "UpdatedAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if err := m._validateUuid(m.GetUserId()); err != nil {
		err = TweetValidationError{
			field:  "UserId",
			reason: "value must be a valid UUID",
			cause:  err,
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return TweetMultiError(errors)
	}

	return nil
}

func (m *Tweet) _validateUuid(uuid string) error {
	if matched := _service_uuidPattern.MatchString(uuid); !matched {
		return errors.New("invalid uuid format")
	}

	return nil
}

// TweetMultiError is an error wrapping multiple validation errors returned by
// Tweet.ValidateAll() if the designated constraints aren't met.
type TweetMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m TweetMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m TweetMultiError) AllErrors() []error { return m }

// TweetValidationError is the validation error returned by Tweet.Validate if
// the designated constraints aren't met.
type TweetValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e TweetValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e TweetValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e TweetValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e TweetValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e TweetValidationError) ErrorName() string { return "TweetValidationError" }

// Error satisfies the builtin error interface
func (e TweetValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sTweet.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = TweetValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = TweetValidationError{}
