// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: api/proto/v1/service.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TwitterAPI_CreateTweet_FullMethodName          = "/api.proto.v1.TwitterAPI/CreateTweet"
	TwitterAPI_GetTweetByID_FullMethodName         = "/api.proto.v1.TwitterAPI/GetTweetByID"
	TwitterAPI_GetUserTweets_FullMethodName        = "/api.proto.v1.TwitterAPI/GetUserTweets"
	TwitterAPI_UpdateTweet_FullMethodName          = "/api.proto.v1.TwitterAPI/UpdateTweet"
	TwitterAPI_DeleteTweet_FullMethodName          = "/api.proto.v1.TwitterAPI/DeleteTweet"
	TwitterAPI_GetSubscribersTweets_FullMethodName = "/api.proto.v1.TwitterAPI/GetSubscribersTweets"
)

// TwitterAPIClient is the client API for TwitterAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TwitterAPIClient interface {
	CreateTweet(ctx context.Context, in *CreateTweetRequest, opts ...grpc.CallOption) (*CreateTweetResponse, error)
	GetTweetByID(ctx context.Context, in *GetTweetByIDRequest, opts ...grpc.CallOption) (*GetTweetByIDResponse, error)
	GetUserTweets(ctx context.Context, in *GetUserTweetsRequest, opts ...grpc.CallOption) (*GetUserTweetsResponse, error)
	UpdateTweet(ctx context.Context, in *UpdateTweetRequest, opts ...grpc.CallOption) (*UpdateTweetResponse, error)
	DeleteTweet(ctx context.Context, in *DeleteTweetRequest, opts ...grpc.CallOption) (*DeleteTweetResponse, error)
	GetSubscribersTweets(ctx context.Context, in *GetSubscribersTweetsRequest, opts ...grpc.CallOption) (*GetSubscribersTweetsResponse, error)
}

type twitterAPIClient struct {
	cc grpc.ClientConnInterface
}

func NewTwitterAPIClient(cc grpc.ClientConnInterface) TwitterAPIClient {
	return &twitterAPIClient{cc}
}

func (c *twitterAPIClient) CreateTweet(ctx context.Context, in *CreateTweetRequest, opts ...grpc.CallOption) (*CreateTweetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateTweetResponse)
	err := c.cc.Invoke(ctx, TwitterAPI_CreateTweet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *twitterAPIClient) GetTweetByID(ctx context.Context, in *GetTweetByIDRequest, opts ...grpc.CallOption) (*GetTweetByIDResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTweetByIDResponse)
	err := c.cc.Invoke(ctx, TwitterAPI_GetTweetByID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *twitterAPIClient) GetUserTweets(ctx context.Context, in *GetUserTweetsRequest, opts ...grpc.CallOption) (*GetUserTweetsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserTweetsResponse)
	err := c.cc.Invoke(ctx, TwitterAPI_GetUserTweets_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *twitterAPIClient) UpdateTweet(ctx context.Context, in *UpdateTweetRequest, opts ...grpc.CallOption) (*UpdateTweetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateTweetResponse)
	err := c.cc.Invoke(ctx, TwitterAPI_UpdateTweet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *twitterAPIClient) DeleteTweet(ctx context.Context, in *DeleteTweetRequest, opts ...grpc.CallOption) (*DeleteTweetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteTweetResponse)
	err := c.cc.Invoke(ctx, TwitterAPI_DeleteTweet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *twitterAPIClient) GetSubscribersTweets(ctx context.Context, in *GetSubscribersTweetsRequest, opts ...grpc.CallOption) (*GetSubscribersTweetsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSubscribersTweetsResponse)
	err := c.cc.Invoke(ctx, TwitterAPI_GetSubscribersTweets_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TwitterAPIServer is the server API for TwitterAPI service.
// All implementations should embed UnimplementedTwitterAPIServer
// for forward compatibility.
type TwitterAPIServer interface {
	CreateTweet(context.Context, *CreateTweetRequest) (*CreateTweetResponse, error)
	GetTweetByID(context.Context, *GetTweetByIDRequest) (*GetTweetByIDResponse, error)
	GetUserTweets(context.Context, *GetUserTweetsRequest) (*GetUserTweetsResponse, error)
	UpdateTweet(context.Context, *UpdateTweetRequest) (*UpdateTweetResponse, error)
	DeleteTweet(context.Context, *DeleteTweetRequest) (*DeleteTweetResponse, error)
	GetSubscribersTweets(context.Context, *GetSubscribersTweetsRequest) (*GetSubscribersTweetsResponse, error)
}

// UnimplementedTwitterAPIServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTwitterAPIServer struct{}

func (UnimplementedTwitterAPIServer) CreateTweet(context.Context, *CreateTweetRequest) (*CreateTweetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateTweet not implemented")
}
func (UnimplementedTwitterAPIServer) GetTweetByID(context.Context, *GetTweetByIDRequest) (*GetTweetByIDResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTweetByID not implemented")
}
func (UnimplementedTwitterAPIServer) GetUserTweets(context.Context, *GetUserTweetsRequest) (*GetUserTweetsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserTweets not implemented")
}
func (UnimplementedTwitterAPIServer) UpdateTweet(context.Context, *UpdateTweetRequest) (*UpdateTweetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateTweet not implemented")
}
func (UnimplementedTwitterAPIServer) DeleteTweet(context.Context, *DeleteTweetRequest) (*DeleteTweetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteTweet not implemented")
}
func (UnimplementedTwitterAPIServer) GetSubscribersTweets(context.Context, *GetSubscribersTweetsRequest) (*GetSubscribersTweetsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSubscribersTweets not implemented")
}
func (UnimplementedTwitterAPIServer) testEmbeddedByValue() {}

// UnsafeTwitterAPIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TwitterAPIServer will
// result in compilation errors.
type UnsafeTwitterAPIServer interface {
	mustEmbedUnimplementedTwitterAPIServer()
}

func RegisterTwitterAPIServer(s grpc.ServiceRegistrar, srv TwitterAPIServer) {
	// If the following call pancis, it indicates UnimplementedTwitterAPIServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TwitterAPI_ServiceDesc, srv)
}

func _TwitterAPI_CreateTweet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTweetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TwitterAPIServer).CreateTweet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TwitterAPI_CreateTweet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TwitterAPIServer).CreateTweet(ctx, req.(*CreateTweetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TwitterAPI_GetTweetByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTweetByIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TwitterAPIServer).GetTweetByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TwitterAPI_GetTweetByID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TwitterAPIServer).GetTweetByID(ctx, req.(*GetTweetByIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TwitterAPI_GetUserTweets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserTweetsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TwitterAPIServer).GetUserTweets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TwitterAPI_GetUserTweets_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TwitterAPIServer).GetUserTweets(ctx, req.(*GetUserTweetsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TwitterAPI_UpdateTweet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateTweetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TwitterAPIServer).UpdateTweet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TwitterAPI_UpdateTweet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TwitterAPIServer).UpdateTweet(ctx, req.(*UpdateTweetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TwitterAPI_DeleteTweet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteTweetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TwitterAPIServer).DeleteTweet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TwitterAPI_DeleteTweet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TwitterAPIServer).DeleteTweet(ctx, req.(*DeleteTweetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TwitterAPI_GetSubscribersTweets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSubscribersTweetsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TwitterAPIServer).GetSubscribersTweets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TwitterAPI_GetSubscribersTweets_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TwitterAPIServer).GetSubscribersTweets(ctx, req.(*GetSubscribersTweetsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TwitterAPI_ServiceDesc is the grpc.ServiceDesc for TwitterAPI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TwitterAPI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.proto.v1.TwitterAPI",
	HandlerType: (*TwitterAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateTweet",
			Handler:    _TwitterAPI_CreateTweet_Handler,
		},
		{
			MethodName: "GetTweetByID",
			Handler:    _TwitterAPI_GetTweetByID_Handler,
		},
		{
			MethodName: "GetUserTweets",
			Handler:    _TwitterAPI_GetUserTweets_Handler,
		},
		{
			MethodName: "UpdateTweet",
			Handler:    _TwitterAPI_UpdateTweet_Handler,
		},
		{
			MethodName: "DeleteTweet",
			Handler:    _TwitterAPI_DeleteTweet_Handler,
		},
		{
			MethodName: "GetSubscribersTweets",
			Handler:    _TwitterAPI_GetSubscribersTweets_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/v1/service.proto",
}
